create table public.game_participants (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  game_id text null,
  user_id text null,
  team_index smallint null,
  score real null,
  constraint game_participants_pkey primary key (id)
) TABLESPACE pg_default;